name: "godot-web-ci export"
on:
  push:
    branches:
      - release-web

env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: snow_wars

jobs:
 export-deploy-web:
   name: Web Export and Deploy
   runs-on: ubuntu-latest
   container:
     image: barichello/godot-ci:3.4.4
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         lfs: true
     - name: Setup
       run: |
         mkdir -v -p ~/.local/share/godot/templates
         mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
     - name: Web Build
       run: |
         mkdir -v -p build/web
         # cd $EXPORT_NAME
         godot -v --export "HTML5" build/web/index.html
     - name: Deploy to Itch
       uses: josephbmanley/butler-publish-itchio-action@master
       env:
           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
           CHANNEL: web
           ITCH_GAME: snowhere-to-run
           ITCH_USER: Oeslian
           PACKAGE: build/web
